server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: health
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger